### ISSUE TITLE
M command returns nothing

### ISSUE THREAD

**Issue by sandro-macchioli** [BenziAhamed/Menu-Bar-Search#14] opened 2021-11-10 13:27 UTC
Hey, I can't understand why I am not getting any results? I created a hotkey, can run the workflow, but no matter what I type after returns nothing. I tried making the m command optional and required, tried the ms command as well, no results. 

Could you please help me figure out what the problem is? Thank you!

Running this on a mac, intel processor, MacOS Big Sur 11.5.2.

**Comment by Korean-David** [comment] 2021-11-10 13:38
The previous version (1.6) may work if you run it on an intel mac.

**Comment by gnestor** [comment] 2021-11-22 20:39
Duplicate of https://github.com/BenziAhamed/Menu-Bar-Search/issues/11

**Comment by BenziAhamed** [comment] 2021-12-30 01:58
Kindly download the version 1.8 and let me know if this is sorted. [View v1.8 worlflow](https://github.com/BenziAhamed/Menu-Bar-Search/blob/ac77d01c6b4ef30c4acd02e075cc2068ffd827ad/Menu%20Bar%20Search.alfredworkflow)

**Closed** 2022-01-09 01:30 UTC

**Comment by mbirth** [comment] 2022-06-28 17:06
After upgrading from 1.6 to 1.8, the `menu` binary was missing from the workflow directory in Alfred's directory on my iCloud storage. After manually copying it there and allowing macOS to run it, the workflow now works fine again.
